version: '3'
services:
  web:
    build: ./web
    ports:
      - "80:80"
    volumes:
      - ./web:/var/www/html

  database:
    build: ./database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sealmo
      MYSQL_USER: sealmo
      MYSQL_PASSWORD: 321cic7,H
  adminphp:
    build: ./adminphp
    ports:
      - "8000:80"
    links:
      - database
